import fs from "fs/promises";
import path from "path";

/**
 * Loader for the BIS "Group 1" recognised-laboratories reference dataset
 * (data/bis-standards-dataset/recognised-laboratories.json, generated by
 * scripts/data-laboratories-convert.ts from the official source CSV).
 *
 * This is a directory, not a capability index: the source data has no
 * per-standard testing scope, no product-category linkage, and no
 * coordinates, so this loader never claims a laboratory can test to a
 * specific standard — see docs/ui/UI_DATA_AND_TRUTH_RULES.md. Callers
 * that want "labs relevant to standard X" must say so is not something
 * this dataset can answer, and should link out to the official BIS
 * laboratory portal instead.
 */
export interface LaboratoryItem {
  id: string;
  slNo: number;
  name: string;
  city: string | null;
  state: string;
  stateRaw: string;
  type: "Private" | "Government";
  oslCode: string;
  recognitionValidUpto: string | null;
  recognitionValidUptoRaw: string;
  currentStatus: "Active" | "Suspended" | "Deferred" | "Unknown";
  remarks: string | null;
  /**
   * City-level coordinates from scripts/data-laboratories-geocode.ts
   * (OpenStreetMap Nominatim, real geocoding of the lab's own city/state —
   * never invented). Null when that city/state combination couldn't be
   * resolved. This is a city-level point, not the lab's exact address —
   * the source recognition list has no street address to geocode.
   */
  latitude: number | null;
  longitude: number | null;
}

interface GeoPoint {
  latitude: number;
  longitude: number;
  displayName: string;
}

let cache: LaboratoryItem[] | null = null;

export async function loadLaboratories(): Promise<LaboratoryItem[]> {
  if (cache) return cache;
  const filePath = path.join(process.cwd(), "data/bis-standards-dataset/recognised-laboratories.json");
  const raw = await fs.readFile(filePath, "utf-8");
  const records = JSON.parse(raw) as Array<Omit<LaboratoryItem, "latitude" | "longitude">>;

  let coordinates: Record<string, GeoPoint | null> = {};
  try {
    const coordPath = path.join(process.cwd(), "data/bis-standards-dataset/laboratory-coordinates.json");
    coordinates = JSON.parse(await fs.readFile(coordPath, "utf-8")) as Record<string, GeoPoint | null>;
  } catch {
    // Not generated yet (npx tsx scripts/data-laboratories-geocode.ts) — the
    // directory still works without a map, just with no coordinates.
  }

  cache = records.map((r) => {
    const point = coordinates[`${r.city ?? ""}|${r.state}`];
    return { ...r, latitude: point?.latitude ?? null, longitude: point?.longitude ?? null };
  });
  return cache;
}

/** Whether a lab's recognition validity date has passed, as of `asOf` (defaults to now). */
export function isRecognitionExpired(lab: LaboratoryItem, asOf: Date = new Date()): boolean {
  if (!lab.recognitionValidUpto) return false;
  return new Date(lab.recognitionValidUpto) < asOf;
}
