import fs from "fs/promises";
import path from "path";

/**
 * Loader for the BIS "Group 1" recognised-laboratories reference dataset
 * (data/bis-standards-dataset/recognised-laboratories.json, generated by
 * scripts/data-laboratories-convert.ts from the official source CSV).
 *
 * This is a directory, not a capability index: the source data has no
 * per-standard testing scope, no product-category linkage, and no
 * coordinates, so this loader never claims a laboratory can test to a
 * specific standard — see docs/ui/UI_DATA_AND_TRUTH_RULES.md. Callers
 * that want "labs relevant to standard X" must say so is not something
 * this dataset can answer, and should link out to the official BIS
 * laboratory portal instead.
 */
export interface LaboratoryItem {
  id: string;
  slNo: number;
  name: string;
  city: string | null;
  state: string;
  stateRaw: string;
  type: "Private" | "Government";
  oslCode: string;
  recognitionValidUpto: string | null;
  recognitionValidUptoRaw: string;
  currentStatus: "Active" | "Suspended" | "Deferred" | "Unknown";
  remarks: string | null;
}

let cache: LaboratoryItem[] | null = null;

export async function loadLaboratories(): Promise<LaboratoryItem[]> {
  if (cache) return cache;
  const filePath = path.join(process.cwd(), "data/bis-standards-dataset/recognised-laboratories.json");
  const raw = await fs.readFile(filePath, "utf-8");
  cache = JSON.parse(raw) as LaboratoryItem[];
  return cache;
}

/** Whether a lab's recognition validity date has passed, as of `asOf` (defaults to now). */
export function isRecognitionExpired(lab: LaboratoryItem, asOf: Date = new Date()): boolean {
  if (!lab.recognitionValidUpto) return false;
  return new Date(lab.recognitionValidUpto) < asOf;
}
